In [2]:
import numpy as np

In [7]:
#Question 1
x=np.array([[1,2,3],[4,5,6]])
y=x.tolist()
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [19]:
#Question 2
Q2=np.array([[1,3,6],[3,0,1],[0,6,1]])
print(R2)
for i in range(1,len(Q2)):
    R2+=Q2[i,i]
print(R2)

2
3


In [29]:
#Question 3
Q3=np.array([[1,2,3],[4,5,6],[3,6,1]])
X=2
Q3List=[]
for k in range(len(Q3)):
    for i in range(len(Q3[k])):
        if Q3[k,i]>X:
            Q3List.append(Q3[k,i])
print(Q3List)

[3, 4, 5, 6, 3, 6]


In [12]:
#Question 4
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[6,5,4],[3,2,1]])
C=A+B
print(C)

[[7 7 7]
 [7 7 7]]


In [11]:
#Question 5
import statistics
Q5=np.array([[1,2,3],[4,5,6],[1,3,2]])
for j in range(len(Q5)):
    h=statistics.mean(Q5[j,:])
    print("Mean of row #",j,": ",h,end=" / ")

Mean of row # 0 :  2 / Mean of row # 1 :  5 / Mean of row # 2 :  2 / 